sonar.projectKey=pebisnice
sonar.projectName=Pebisnice
sonar.host.url=https://sonar.digi-x.store
sonar.sources=app,components,lib,proxy.ts,auth.ts,auth.config.ts,next.config.ts,scripts
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts
sonar.exclusions=**/node_modules/**,**/.next/**,components/ui/**,supabase/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
